-- MySQL Script generated by MySQL Workbench
-- Sun Jan 13 04:52:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`durations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`durations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`durations` (
  `minutes` INT NOT NULL,
  PRIMARY KEY (`minutes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`films` ;

CREATE TABLE IF NOT EXISTS `mydb`.`films` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `DURATION_FK_idx` (`duration` ASC),
  CONSTRAINT `DURATION_FK`
    FOREIGN KEY (`duration`)
    REFERENCES `mydb`.`durations` (`minutes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `film_id` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `price` INT NOT NULL,
  INDEX `FILM_FK_idx` (`film_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `FILM_FK`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tickets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tickets` (
  `ticket_no` INT NOT NULL AUTO_INCREMENT,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`ticket_no`),
  INDEX `SESSION_FK_idx` (`session_id` ASC),
  CONSTRAINT `SESSION_FK`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`sessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `mydb`.`durations` (`minutes`) VALUES ('60');
INSERT INTO `mydb`.`durations` (`minutes`) VALUES ('90');
INSERT INTO `mydb`.`durations` (`minutes`) VALUES ('120');

INSERT INTO `mydb`.`films` (`title`, `duration`) VALUES ('Выживший', '120');
INSERT INTO `mydb`.`films` (`title`, `duration`) VALUES ('Елки Новые', '90');
INSERT INTO `mydb`.`films` (`title`, `duration`) VALUES ('Дом который построил Джек', '120');
INSERT INTO `mydb`.`films` (`title`, `duration`) VALUES ('Т 34', '60');
INSERT INTO `mydb`.`films` (`title`, `duration`) VALUES ('Полицейский с рублевки', '60');
INSERT INTO `mydb`.`films` (`title`, `duration`) VALUES ('Мстители', '90');
INSERT INTO `mydb`.`films` (`title`, `duration`) VALUES ('Дэдпул', '90');
INSERT INTO `mydb`.`sessions` (`film_id`, `date_time`, `price`) VALUES ('2', '2019-01-13 15:00:00', 200);
INSERT INTO `mydb`.`sessions` (`film_id`, `date_time`, `price`) VALUES ('2', '2019-01-13 20:00:00', 300);
INSERT INTO `mydb`.`sessions` (`film_id`, `date_time`, `price`) VALUES ('2', '2019-01-13 16:00:00', 100);
INSERT INTO `mydb`.`sessions` (`film_id`, `date_time`, `price`) VALUES ('4', '2019-01-13 11:00:00', 200);
INSERT INTO `mydb`.`sessions` (`film_id`, `date_time`, `price`) VALUES ('1', '2019-01-13 16:00:00', 500);
INSERT INTO `mydb`.`sessions` (`film_id`, `date_time`, `price`) VALUES ('4', '2019-01-13 17:00:00', 600);
INSERT INTO `mydb`.`sessions` (`film_id`, `date_time`, `price`) VALUES ('6', '2019-01-13 15:00:00', 200);
INSERT INTO `mydb`.`sessions` (`film_id`, `date_time`, `price`) VALUES ('2', '2019-01-13 14:00:00', 500);

INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (8);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (5);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (4);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (6);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (7);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (8);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (2);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (7);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (7);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (6);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (8);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (8);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (2);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (6);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (4);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (8);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (5);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (7);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (6);
INSERT INTO `mydb`.`tickets` (`session_id`) VALUES (8);